version: '3'
services:

  #PHP Service
  app:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    depends_on:
      - db
    container_name: app
    working_dir: ${WORKING_DIR}
    environment:
      APP_ENV: local
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 # for xdebug
      PHP_IDE_CONFIG: serverName=docker # for xdebug servername
    volumes:
      - ./:${WORKING_DIR}
      - ./docker/php/conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini # comment out this will disable xdebug
      - ./docker/supervisord/supervisord.conf:/etc/supervisor/supervisord.conf # mapping supervisord.conf
    networks:
      - app-network

  #Nginx Service
  webserver:
    platform: linux/amd64
    image: nginx:alpine
    container_name: webserver
    working_dir: ${WORKING_DIR}
    depends_on:
      - app
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ./:${WORKING_DIR}
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #Database
  db:
    # platform: linux/x86_64
    # image: mysql:5.7
    image: mariadb:10.5.8
    container_name: db
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_qlassword']
    environment:
      MYSQL_DATABASE: "${DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
        - "3306:3306"
    volumes:
      - ./docker/db/dbdata:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
